<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Mayas-MacBook-Air.local" failures="1" tests="3" name="ExceptionTest" time="0.334" errors="0" timestamp="2024-11-16T14:46:12 EST">
  <testcase classname="testNGExceptionTest.TestException" name="testAdd" time="0.119"/>
  <testcase classname="testNGExceptionTest.TestException" name="testArthmenticException" time="0.02">
    <failure type="org.testng.TestException" message="
Method TestException.testArthmenticException()[pri:0, instance:testNGExceptionTest.TestException@34bde49d] should have thrown an exception of type class java.lang.ArithmeticException">
      <![CDATA[org.testng.TestException: 
Method TestException.testArthmenticException()[pri:0, instance:testNGExceptionTest.TestException@34bde49d] should have thrown an exception of type class java.lang.ArithmeticException
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testArthmenticException -->
  <testcase classname="testNGExceptionTest.TestException" name="testSubtract" time="0.005"/>
</testsuite> <!-- ExceptionTest -->
